version: '3.8'

services:
  db:
    image: postgres
    container_name: ossystem-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
